// GuitarGuru data layer: chords, curriculum, songs, patterns, levels, achievements, quizzes.
// All frets arrays are low E -> high E. -1 = mute, 0 = open.
'use strict';

const CHORDS = {
  Em:    { name: 'E minor',    frets: [0,2,2,0,0,0],  fingers: [0,2,3,0,0,0], diff: 1,
           tip: 'Your very first chord. Two fingers, all six strings ring out. Press just behind the frets.' },
  Am:    { name: 'A minor',    frets: [-1,0,2,2,1,0], fingers: [0,0,2,3,1,0], diff: 1,
           tip: 'Skip the low E string. Keep your thumb behind the neck and curl your fingers.' },
  D:     { name: 'D major',    frets: [-1,-1,0,2,3,2],fingers: [0,0,0,1,3,2], diff: 2,
           tip: 'The little triangle. Strum only the thin 4 strings — aim from the D string down.' },
  A:     { name: 'A major',    frets: [-1,0,2,2,2,0], fingers: [0,0,1,2,3,0], diff: 2,
           tip: 'Three fingers squeezed in fret 2. Squash them together — fingertips, not pads.' },
  E:     { name: 'E major',    frets: [0,2,2,1,0,0],  fingers: [0,2,3,1,0,0], diff: 2,
           tip: 'The big open E. Same shape as Am moved one string over. All six strings ring.' },
  G:     { name: 'G major',    frets: [3,2,0,0,0,3],  fingers: [2,1,0,0,0,3], diff: 2,
           tip: 'Stretch! Anchor your ring finger on the high E and reach the others over.' },
  C:     { name: 'C major',    frets: [-1,3,2,0,1,0], fingers: [0,3,2,0,1,0], diff: 3,
           tip: 'The stair-step chord. Arch your fingers so the open G and E strings ring clear.' },
  Dm:    { name: 'D minor',    frets: [-1,-1,0,2,3,1],fingers: [0,0,0,2,3,1], diff: 3,
           tip: 'Like D but sadder — pinky-free version uses fingers 1, 2 and 3. Top 4 strings only.' },
  A7:    { name: 'A7',         frets: [-1,0,2,0,2,0], fingers: [0,0,1,0,2,0], diff: 1,
           tip: 'Two fingers, huge bluesy sound. The gap in the middle is what makes it a 7th.' },
  D7:    { name: 'D7',         frets: [-1,-1,0,2,1,2],fingers: [0,0,0,2,1,3], diff: 2,
           tip: 'An upside-down triangle vs D. Great partner for G in hundreds of songs.' },
  E7:    { name: 'E7',         frets: [0,2,0,1,0,0],  fingers: [0,2,0,1,0,0], diff: 1,
           tip: 'E major minus one finger. Lift your ring finger off and let the D string ring open.' },
  G7:    { name: 'G7',         frets: [3,2,0,0,0,1],  fingers: [3,2,0,0,0,1], diff: 2,
           tip: 'G with the melancholy top note. Index finger on the high E, first fret.' },
  Cadd9: { name: 'Cadd9',      frets: [-1,3,2,0,3,3], fingers: [0,2,1,0,3,4], diff: 3,
           tip: 'The secret weapon: swap with G keeping fingers 3 & 4 planted. Instant smooth changes.' },
  Asus2: { name: 'Asus2',      frets: [-1,0,2,2,0,0], fingers: [0,0,1,2,0,0], diff: 1,
           tip: 'A dreamy, easy cousin of A. Two fingers — a perfect first-week win.' },
  Dsus4: { name: 'Dsus4',      frets: [-1,-1,0,2,3,3],fingers: [0,0,0,1,3,4], diff: 2,
           tip: 'Add your pinky to D, then lift it off. That add-lift move is a classic embellishment.' },
  Em7:   { name: 'Em7',        frets: [0,2,2,0,3,0],  fingers: [0,1,2,0,3,0], diff: 2,
           tip: 'Em with a jangly top. Pairs beautifully with Cadd9 and G.' },
  Fmaj7: { name: 'Fmaj7',      frets: [-1,-1,3,2,1,0],fingers: [0,0,3,2,1,0], diff: 3,
           tip: 'The friendly gateway to the dreaded F. Top 4 strings, walk your fingers down the stairs.' },
  F:     { name: 'F (mini)',   frets: [-1,-1,3,2,1,1],fingers: [0,0,3,2,1,1], diff: 4,
           tip: 'The boss battle. Your index finger flattens across TWO strings at fret 1. Squeeze and be patient.' },
};

// Standard tuning open-string MIDI notes, low E -> high E.
const OPEN_MIDI = [40, 45, 50, 55, 59, 64];
const TUNING = [
  { name: 'E2', midi: 40, label: 'E (thickest)' },
  { name: 'A2', midi: 45, label: 'A' },
  { name: 'D3', midi: 50, label: 'D' },
  { name: 'G3', midi: 55, label: 'G' },
  { name: 'B3', midi: 59, label: 'B' },
  { name: 'E4', midi: 64, label: 'e (thinnest)' },
];

// Strumming patterns. 8 slots per bar (eighth notes). 'D'=down, 'U'=up, '-'=miss (keep arm moving).
const STRUM_PATTERNS = {
  d4:      { name: 'Four on the floor', slots: ['D','-','D','-','D','-','D','-'], bpm: 60,
             desc: 'One down-strum per beat. Your arm is a metronome.' },
  d8:      { name: 'Down eighths',      slots: ['D','D','D','D','D','D','D','D'], bpm: 70,
             desc: 'Downs on every half beat. Loosen that wrist.' },
  dduThree:{ name: 'Waltz D-DU',        slots: ['D','-','D','U','D','U'], bpm: 80, beats: 3,
             desc: '3/4 time: down, down-up, down-up. For Amazing Grace and other waltzes.' },
  ddu:     { name: 'D-D-DU',            slots: ['D','-','D','-','D','U','D','-'], bpm: 70,
             desc: 'Your first up-strum. Keep downs on the beat, sneak the up in.' },
  oldFaithful: { name: 'Old Faithful (D-DU-UDU)', slots: ['D','-','D','U','-','U','D','U'], bpm: 70,
             desc: 'THE pattern. Works on thousands of songs. Miss the strings on beat 3 but keep the arm swinging.' },
  folk:    { name: 'Folk pattern',      slots: ['D','-','D','U','D','U','D','U'], bpm: 75,
             desc: 'Busy and driving. Down on 1, then down-ups the rest of the way.' },
  chuck:   { name: 'Muted chuck',       slots: ['D','-','X','U','-','U','X','U'], bpm: 75,
             desc: "X = percussive chuck: relax fret hand slightly and slap the strums dead. Instant groove." },
};

// Songs: traditional / public-domain. bars = chord per bar (or split bars as arrays).
const SONGS = [
  { id: 'jam-em-am', title: 'Two-Chord Campfire Jam', artist: 'GuitarGuru original', day: 3,
    chords: ['Em','Am'], pattern: 'd4', bpm: 60, timeSig: 4,
    bars: ['Em','Em','Am','Am','Em','Em','Am','Am'],
    note: 'Your first real music. Loop it until the change feels boring — boring means you own it.' },
  { id: 'saints', title: 'When the Saints Go Marching In', artist: 'Traditional', day: 6,
    chords: ['G','D7','C'], pattern: 'd4', bpm: 75, timeSig: 4,
    bars: ['G','G','G','G','G','G','D7','D7','G','G','C','C','G','D7','G','G'],
    lyric: 'Oh when the saints... go marching in...',
    note: 'Everybody knows it, everybody sings along. Your first three-chord song.' },
  { id: 'birthday', title: 'Happy Birthday', artist: 'Traditional (public domain)', day: 7,
    chords: ['G','D7','C'], pattern: 'dduThree', bpm: 80, timeSig: 3,
    bars: ['G','D7','D7','G','G','C',['G','D7'],'G'],
    note: 'The highest value-per-minute song ever. Learn once, be a hero at every party forever.' },
  { id: 'clementine', title: 'Oh My Darling, Clementine', artist: 'Traditional', day: 8,
    chords: ['G','D7'], pattern: 'dduThree', bpm: 85, timeSig: 3,
    bars: ['G','G','G','D7','D7','D7','G',['D7','G']],
    note: 'Two chords in waltz time. Focus on smooth, early D7 changes.' },
  { id: 'blues12', title: '12-Bar Blues in A', artist: 'The oldest trick in the book', day: 10,
    chords: ['A7','D7','E7'], pattern: 'd8', bpm: 80, timeSig: 4,
    bars: ['A7','A7','A7','A7','D7','D7','A7','A7','E7','D7','A7','E7'],
    note: 'The DNA of rock and roll. Loop it and you are officially playing the blues.' },
  { id: 'grace', title: 'Amazing Grace', artist: 'Traditional', day: 11,
    chords: ['G','C','D','D7','Em'], pattern: 'dduThree', bpm: 70, timeSig: 3,
    bars: ['G','G','C','G','G','Em','D','D7','G','G','C','G','G','D','G','G'],
    lyric: 'A-ma-zing grace, how sweet the sound...',
    note: 'Slow and beautiful. Let every chord ring. Waltz strum: D, D-U, D-U.' },
  { id: 'auldlang', title: 'Auld Lang Syne', artist: 'Traditional', day: 12,
    chords: ['G','Cadd9','D','Em'], pattern: 'ddu', bpm: 75, timeSig: 4,
    bars: ['G','D','G','Cadd9','G','D','Em',['Cadd9','G']],
    note: 'Uses your new Cadd9-G trick: fingers 3 and 4 never move.' },
  { id: 'rising-sun', title: 'House of the Rising Sun', artist: 'Traditional', day: 15,
    chords: ['Am','C','D','F','E'], pattern: 'dduThree', bpm: 78, timeSig: 3,
    bars: ['Am','C','D','F','Am','C','E','E','Am','C','D','F','Am','E','Am','Am'],
    note: 'The moody classic. Use Fmaj7 if mini-F is not ready yet — it sounds great here.' },
  { id: 'scarborough', title: 'Scarborough Fair', artist: 'Traditional', day: 18,
    chords: ['Em','D','G','A'], pattern: 'dduThree', bpm: 80, timeSig: 3,
    bars: ['Em','Em','D','Em','Em','G',['Em','A'],'Em','Em','G','D','Em',['Em','D'],['Em','A'],'Em','Em'],
    note: 'Haunting and gorgeous. Try fingerpicking it once the strummed version flows.' },
  { id: 'wildrover', title: 'The Wild Rover', artist: 'Traditional', day: 23,
    chords: ['G','C','D','D7'], pattern: 'oldFaithful', bpm: 90, timeSig: 4,
    bars: ['G','G','C','C','G','G','D','D7','G','C','G',['G','D7'],'G','C',['G','D'],'G'],
    note: 'A pub singalong. Old Faithful strum at full speed. And it’s no, nay, never!' },
];

const LEVELS = [
  { xp: 0,     title: 'Fresh Strings' },
  { xp: 100,   title: 'String Plucker' },
  { xp: 250,   title: 'Chord Curious' },
  { xp: 450,   title: 'Steady Strummer' },
  { xp: 700,   title: 'Campfire Apprentice' },
  { xp: 1000,  title: 'Rhythm Rookie' },
  { xp: 1400,  title: 'Chord Wrangler' },
  { xp: 1900,  title: 'Groove Builder' },
  { xp: 2500,  title: 'Song Slinger' },
  { xp: 3200,  title: 'Campfire Hero' },
  { xp: 4000,  title: 'Fretboard Friend' },
  { xp: 5000,  title: 'Acoustic Ace' },
];

const ACHIEVEMENTS = [
  { id: 'first-steps',  icon: '🎸', name: 'First Steps',      desc: 'Complete Day 1' },
  { id: 'tuned-up',     icon: '🎯', name: 'Tuned Up',         desc: 'Use the tuner for the first time' },
  { id: 'first-chord',  icon: '✋', name: 'First Chord',      desc: 'Learn your first chord' },
  { id: 'collector-5',  icon: '🖐️', name: 'Chord Collector', desc: 'Learn 5 chords' },
  { id: 'collector-10', icon: '🤘', name: 'Chord Hoarder',    desc: 'Learn 10 chords' },
  { id: 'collector-all',icon: '👑', name: 'Chord Royalty',    desc: 'Learn every chord in the library' },
  { id: 'first-song',   icon: '🎵', name: 'First Song',       desc: 'Play your first song' },
  { id: 'songbird-3',   icon: '🐦', name: 'Songbird',         desc: 'Play 3 different songs' },
  { id: 'songbird-6',   icon: '🦅', name: 'Setlist Builder',  desc: 'Play 6 different songs' },
  { id: 'streak-3',     icon: '🔥', name: 'Kindling',         desc: '3-day practice streak' },
  { id: 'streak-7',     icon: '🔥', name: 'On Fire',          desc: '7-day practice streak' },
  { id: 'streak-14',    icon: '🌋', name: 'Unstoppable',      desc: '14-day practice streak' },
  { id: 'streak-30',    icon: '☄️', name: 'Force of Nature',  desc: '30-day practice streak' },
  { id: 'changes-30',   icon: '⚡', name: 'Quick Fingers',    desc: '30+ changes in one minute' },
  { id: 'changes-45',   icon: '⚡', name: 'Speed Demon',      desc: '45+ changes in one minute' },
  { id: 'changes-60',   icon: '🌩️', name: 'Lightning Hands', desc: '60+ changes in one minute' },
  { id: 'metronome-10', icon: '🕰️', name: 'Metronome Mate',  desc: '10 metronome sessions' },
  { id: 'blues',        icon: '😎', name: 'Blues Initiate',   desc: 'Play the 12-bar blues' },
  { id: 'f-conqueror',  icon: '⚔️', name: 'F-Conqueror',      desc: 'Learn the F chord — the boss battle' },
  { id: 'quiz-ace',     icon: '🧠', name: 'Theory Brain',     desc: 'Score 100% on any quiz' },
  { id: 'level-5',      icon: '⭐', name: 'Rising Star',      desc: 'Reach level 5' },
  { id: 'level-10',     icon: '🌟', name: 'Campfire Hero',    desc: 'Reach level 10' },
  { id: 'week-1',       icon: '🥉', name: 'Week One Done',    desc: 'Complete days 1–7' },
  { id: 'graduate',     icon: '🎓', name: 'Graduate',         desc: 'Complete all 30 days' },
];

// ---- 30-day curriculum ----------------------------------------------------
// Activity types:
//  read            {text}                         — coaching card, mark as read
//  tune            {}                             — open tuner, tune all 6 strings
//  chord           {chord}                        — learn/practice chord (opens diagram + audio)
//  changes         {pair:[a,b], target}           — one-minute changes with target
//  strum           {pattern, bpm, minutes}        — strum trainer
//  song            {song}                         — play-along
//  quiz            {quiz}                         — quiz id
//  free            {text, minutes}                — freeform practice with timer
const DAYS = [
  { day: 1, phase: 1, title: 'Meet Your Guitar', minutes: 15,
    goal: 'Hold the guitar, get it in tune, and play your very first chord.',
    activities: [
      { type: 'read', xp: 10, title: 'How to sit & hold', text: 'Sit on a chair (no armrests). Rest the guitar waist on your right thigh. Back straight, both feet flat. Left thumb behind the neck — like gently squeezing a lemon, not strangling it. Press strings with fingertips, right behind the fret wire.' },
      { type: 'read', xp: 10, title: 'The one rule of practice', text: 'Science says: 15 focused minutes EVERY day beats 2 hours once a week. Your brain wires new finger skills during sleep — daily reps + nightly sleep = fast progress. Protect the streak.' },
      { type: 'tune', xp: 20, title: 'Tune up with the tuner', text: 'Strings from thick to thin: E-A-D-G-B-E ("Eddie Ate Dynamite, Good Bye Eddie"). Pluck one string, watch the needle, turn the peg slowly.' },
      { type: 'chord', chord: 'Em', xp: 25, title: 'Your first chord: Em', text: 'Two fingers. Strum all six strings slowly, one at a time — every string should ring. Buzzing? Move fingers closer to the fret and press with tips.' },
      { type: 'free', xp: 15, minutes: 3, title: 'Strum & sing the win', text: 'Strum Em once per beat for 3 minutes. Congratulations — that sound is YOU playing guitar, on day one.' },
    ]},
  { day: 2, phase: 1, title: 'Two Chords & a Beat', minutes: 15,
    goal: 'Add Am and make your first chord change.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: 'Always start in tune — your ear is learning too.' },
      { type: 'chord', chord: 'Am', xp: 25, title: 'New chord: Am', text: 'Three fingers, skip the thick E string. Check every string rings.' },
      { type: 'chord', chord: 'Em', xp: 10, title: 'Review: Em', text: 'Yesterday’s chord. Form it, strum it, string-by-string check.' },
      { type: 'changes', pair: ['Em','Am'], target: 10, xp: 30, title: 'One-minute changes: Em ↔ Am', text: 'The single fastest way to learn chords, proven by millions of learners: switch back and forth as many times as you can in 60 seconds. Sloppy is fine — speed first, accuracy follows.' },
      { type: 'strum', pattern: 'd4', bpm: 60, minutes: 3, xp: 20, title: 'Strum with the metronome', text: 'Down-strums on the click, alternating Em and Am each bar. Locking to a beat from day 2 is a superpower.' },
    ]},
  { day: 3, phase: 1, title: 'The D Chord & First Jam', minutes: 15,
    goal: 'Learn D and play your first real progression.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: 'Quick check — new strings drift.' },
      { type: 'chord', chord: 'D', xp: 25, title: 'New chord: D', text: 'The triangle. Strum only from the D string down — aiming is a skill, be patient.' },
      { type: 'changes', pair: ['Em','Am'], target: 15, xp: 20, title: 'Changes: Em ↔ Am (beat 10+)', text: 'Beat yesterday’s score. The app remembers your best.' },
      { type: 'changes', pair: ['Am','D'], target: 8, xp: 25, title: 'Changes: Am ↔ D', text: 'New pair. Notice finger 1 barely moves — small moves win.' },
      { type: 'song', song: 'jam-em-am', xp: 30, title: 'First jam: Two-Chord Campfire', text: 'Play along with the moving chart. You are officially making music.' },
    ]},
  { day: 4, phase: 1, title: 'Easy Wins: Asus2 & A', minutes: 15,
    goal: 'Pick up two chords that share one shape.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'Asus2', xp: 20, title: 'New chord: Asus2', text: 'Two fingers, dreamy sound. An instant win.' },
      { type: 'chord', chord: 'A', xp: 25, title: 'New chord: A', text: 'Add one finger to Asus2. Three fingers in one fret — snuggle them in a diagonal line.' },
      { type: 'changes', pair: ['A','D'], target: 8, xp: 25, title: 'Changes: A ↔ D', text: 'The most common change in pop music. Finger 1 is your pivot.' },
      { type: 'strum', pattern: 'd8', bpm: 65, minutes: 3, xp: 20, title: 'Down eighths', text: 'Two downs per beat on A. Relax the wrist — the pick should brush, not dig.' },
    ]},
  { day: 5, phase: 1, title: 'The Mighty G', minutes: 18,
    goal: 'Learn G and your first up-strums.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'G', xp: 25, title: 'New chord: G', text: 'The big stretch. Place finger 3 first, then reach the others. It WILL feel awkward for 2 days — that is normal and temporary.' },
      { type: 'changes', pair: ['G','D'], target: 8, xp: 25, title: 'Changes: G ↔ D', text: 'Finger 3 stays on the same string. Watch it.' },
      { type: 'strum', pattern: 'ddu', bpm: 65, minutes: 4, xp: 25, title: 'First up-strum: D-D-DU', text: 'Ups hit only the thin 3-4 strings — that is correct, not cheating.' },
      { type: 'changes', pair: ['Em','Am'], target: 20, xp: 15, title: 'Speed round: Em ↔ Am', text: 'Old pair, new speed. Feel how far you have come since day 2?' },
    ]},
  { day: 6, phase: 1, title: 'C Major & Three-Chord Magic', minutes: 18,
    goal: 'Learn C and play a real three-chord song.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'C', xp: 25, title: 'New chord: C', text: 'The stair-step. Arch fingers high so open strings ring. Strum from the A string down.' },
      { type: 'chord', chord: 'D7', xp: 20, title: 'New chord: D7', text: 'Easy bonus chord — the upside-down triangle. You need it for tomorrow’s crowd-pleaser.' },
      { type: 'changes', pair: ['C','G'], target: 8, xp: 25, title: 'Changes: C ↔ G', text: 'The classic. Move fingers 1-2 as a glued-together unit.' },
      { type: 'song', song: 'saints', xp: 35, title: 'Song: When the Saints', text: 'G, C and D7. Sing along — nobody is listening.' },
    ]},
  { day: 7, phase: 1, title: 'Week 1 Victory Lap', minutes: 15,
    goal: 'Review everything and bank your first crowd-pleaser.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'changes', pair: ['C','G'], target: 12, xp: 20, title: 'Changes: C ↔ G', text: 'Push your best score up.' },
      { type: 'changes', pair: ['G','D'], target: 12, xp: 20, title: 'Changes: G ↔ D', text: 'Then this one.' },
      { type: 'song', song: 'birthday', xp: 35, title: 'Song: Happy Birthday', text: 'The most useful song on Earth. Waltz strum: D, D-U, D-U.' },
      { type: 'quiz', quiz: 'week1', xp: 30, title: 'Week 1 quiz', text: 'Five quick questions. Prove the knowledge stuck.' },
    ]},

  { day: 8, phase: 2, title: 'Old Faithful', minutes: 18,
    goal: 'Learn the strumming pattern that plays a thousand songs.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'strum', pattern: 'oldFaithful', bpm: 60, minutes: 5, xp: 35, title: 'THE pattern: D-DU-UDU', text: 'Down, down-up, miss, up-down-up. Keep the arm swinging like a pendulum even on the miss. Slow first — speed is free later.' },
      { type: 'changes', pair: ['Am','C'], target: 10, xp: 20, title: 'Changes: Am ↔ C', text: 'One finger moves. ONE. Find it.' },
      { type: 'song', song: 'clementine', xp: 30, title: 'Song: Clementine', text: 'Two chords in 3/4 — all your focus goes to rhythm.' },
    ]},
  { day: 9, phase: 2, title: 'Minor Moods: Dm & E', minutes: 18,
    goal: 'Complete your open-chord starter set.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'Dm', xp: 25, title: 'New chord: Dm', text: 'The saddest chord in the room. Top four strings.' },
      { type: 'chord', chord: 'E', xp: 25, title: 'New chord: E', text: 'Am shape shifted one string toward the floor. All six strings — huge sound.' },
      { type: 'changes', pair: ['Am','E'], target: 10, xp: 25, title: 'Changes: Am ↔ E', text: 'Same shape, different strings. Keep the shape glued while it slides.' },
      { type: 'strum', pattern: 'oldFaithful', bpm: 70, minutes: 4, xp: 20, title: 'Old Faithful, faster', text: 'Yesterday’s pattern +10 bpm, cycling Am → Dm → E.' },
    ]},
  { day: 10, phase: 2, title: 'Blues Day', minutes: 18,
    goal: 'Learn 7th chords and play the 12-bar blues.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'A7', xp: 15, title: 'New chord: A7', text: 'Two fingers. Instant blues.' },
      { type: 'chord', chord: 'E7', xp: 15, title: 'New chord: E7', text: 'E minus a finger. The easiest chord upgrade ever.' },
      { type: 'song', song: 'blues12', xp: 40, title: 'The 12-bar blues', text: 'The DNA of Chuck Berry, Elvis and everyone since. Loop it, swagger optional but recommended.' },
      { type: 'changes', pair: ['A7','D7'], target: 12, xp: 20, title: 'Changes: A7 ↔ D7', text: 'Blues changes, smooth and lazy.' },
    ]},
  { day: 11, phase: 2, title: 'Waltz Time', minutes: 18,
    goal: 'Master 3/4 time with Amazing Grace.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'strum', pattern: 'dduThree', bpm: 70, minutes: 4, xp: 25, title: '3/4 strum: D, DU, DU', text: 'Count ONE-two-three. Lean on beat one.' },
      { type: 'song', song: 'grace', xp: 40, title: 'Song: Amazing Grace', text: 'Slow, gorgeous, forgiving. Let chords ring into each other.' },
      { type: 'changes', pair: ['G','Em'], target: 12, xp: 20, title: 'Changes: G ↔ Em', text: 'Happy to sad in one move.' },
    ]},
  { day: 12, phase: 2, title: 'The Cadd9 Cheat Code', minutes: 18,
    goal: 'Learn the two-finger anchor trick that makes changes effortless.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'Cadd9', xp: 25, title: 'New chord: Cadd9', text: 'Sounds fancy, plays easy. Fingers 3 & 4 sit exactly where they sit in G.' },
      { type: 'chord', chord: 'Em7', xp: 20, title: 'New chord: Em7', text: 'Same anchor fingers AGAIN. G → Cadd9 → Em7 with two fingers never moving.' },
      { type: 'changes', pair: ['G','Cadd9'], target: 14, xp: 25, title: 'Changes: G ↔ Cadd9', text: 'Anchor fingers stay planted. This should quickly become your fastest pair.' },
      { type: 'song', song: 'auldlang', xp: 35, title: 'Song: Auld Lang Syne', text: 'Your anchor trick in the wild.' },
    ]},
  { day: 13, phase: 2, title: 'Dynamics & Groove', minutes: 15,
    goal: 'Make the same chords sound twice as good.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'read', xp: 15, title: 'Loud & quiet', text: 'Play a bar QUIET (brush the top 3 strings) then a bar LOUD (full swing). Dynamics separate players from strummers. Also: accent beat 1 of every bar — just slightly harder.' },
      { type: 'strum', pattern: 'folk', bpm: 75, minutes: 4, xp: 25, title: 'Folk pattern', text: 'Busier pattern. Accent beat 1, whisper the rest.' },
      { type: 'changes', pair: ['C','D'], target: 12, xp: 20, title: 'Changes: C ↔ D', text: 'A tricky lift-everything change. Slow reps beat fast flails.' },
      { type: 'free', xp: 20, minutes: 4, title: 'Loud/quiet song run', text: 'Play any song you know: verse quiet, chorus loud. Feel the difference?' },
    ]},
  { day: 14, phase: 2, title: 'Week 2 Boss Check', minutes: 18,
    goal: 'Test every pair, then quiz out of week 2.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'changes', pair: ['G','C'], target: 15, xp: 20, title: 'Best score: G ↔ C', text: 'Personal-best hunting, round 1.' },
      { type: 'changes', pair: ['Am','E'], target: 15, xp: 20, title: 'Best score: Am ↔ E', text: 'Round 2.' },
      { type: 'song', xp: 30, title: 'Pick your favorite song', song: 'saints', text: 'Play any song from the Songs tab start to finish. Saints is preloaded, but your call.' },
      { type: 'quiz', quiz: 'week2', xp: 30, title: 'Week 2 quiz', text: 'Rhythm, 7ths, and anchor fingers.' },
    ]},

  { day: 15, phase: 3, title: 'House of the Rising Sun', minutes: 20,
    goal: 'Start the most famous beginner song of all time.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'Fmaj7', xp: 25, title: 'New chord: Fmaj7', text: 'The friendly F. Walk fingers down the staircase. You will meet its scary sibling on day 22.' },
      { type: 'changes', pair: ['C','Fmaj7'], target: 10, xp: 25, title: 'Changes: C ↔ Fmaj7', text: 'Keep finger 1 hovering low.' },
      { type: 'song', song: 'rising-sun', xp: 40, title: 'Song: House of the Rising Sun', text: 'Take it slow, it is long. Getting through it at ANY speed today is the win.' },
    ]},
  { day: 16, phase: 3, title: 'Fingerpicking 101', minutes: 18,
    goal: 'Ditch the pick for a day and learn a picking pattern.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'read', xp: 15, title: 'Thumb + 3 fingers', text: 'Thumb (p) plays strings 6-5-4. Index (i) plays 3, middle (m) plays 2, ring (a) plays 1. Rest your forearm, hover the hand, pluck from the knuckle.' },
      { type: 'free', xp: 30, minutes: 5, title: 'Pattern: p-i-m-a', text: 'Hold Em. Pluck: thumb(6), index(3), middle(2), ring(1). Slow loop. Then try on Am (thumb plays string 5) and C.' },
      { type: 'free', xp: 25, minutes: 4, title: 'Picked Rising Sun', text: 'Play House of the Rising Sun chords with p-i-m-a instead of strums. Instant goosebumps.' },
    ]},
  { day: 17, phase: 3, title: 'Embellishments', minutes: 15,
    goal: 'Make plain chords sparkle with sus tricks.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'Dsus4', xp: 20, title: 'New chord: Dsus4', text: 'D plus pinky. The add-lift move you have heard in a hundred intros.' },
      { type: 'free', xp: 25, minutes: 4, title: 'D → Dsus4 → D loop', text: 'Strum D, add pinky (Dsus4), strum, lift, strum. Do the same with A → Asus2. Congratulations, you improvise now.' },
      { type: 'strum', pattern: 'oldFaithful', bpm: 80, minutes: 4, xp: 25, title: 'Old Faithful at 80', text: 'Cycle G → Cadd9 → Em7 → D with embellishments where you dare.' },
    ]},
  { day: 18, phase: 3, title: 'Scarborough Fair', minutes: 18,
    goal: 'A haunting song that makes you sound advanced.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'changes', pair: ['Em','D'], target: 14, xp: 20, title: 'Changes: Em ↔ D', text: 'The backbone of today’s song.' },
      { type: 'song', song: 'scarborough', xp: 40, title: 'Song: Scarborough Fair', text: 'Waltz time, minor key, maximum mystique.' },
      { type: 'free', xp: 20, minutes: 4, title: 'Fingerpick a verse', text: 'One verse with p-i-m-a picking. Slow is beautiful here.' },
    ]},
  { day: 19, phase: 3, title: 'Percussive Strumming', minutes: 15,
    goal: 'Add the muted “chuck” that makes rhythm playing groove.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'read', xp: 15, title: 'The chuck', text: 'Mid-strum, relax your fret hand so fingers touch strings without pressing — the strum becomes a dead “chk”. It is a drum hiding in your guitar.' },
      { type: 'strum', pattern: 'chuck', bpm: 70, minutes: 5, xp: 30, title: 'Muted chuck pattern', text: 'D, chuck, up... it will feel weird for exactly ten minutes. Then it will feel amazing.' },
      { type: 'changes', pair: ['D','Dm'], target: 12, xp: 20, title: 'Changes: D ↔ Dm', text: 'One finger swap, whole mood swap.' },
    ]},
  { day: 20, phase: 3, title: 'Reading Music (the Easy Kind)', minutes: 15,
    goal: 'Learn to read chord charts and tab so any song is open to you.',
    activities: [
      { type: 'read', xp: 20, title: 'Chord charts & tab', text: 'Chord chart: 6 vertical lines = strings (thickest left), horizontal = frets, dots = fingers, X = skip, O = open. Tab: 6 horizontal lines (thinnest on TOP), numbers = fret to press. Read left to right. That is genuinely all of it.' },
      { type: 'quiz', quiz: 'reading', xp: 30, title: 'Chart-reading quiz', text: 'Decode diagrams like a pro.' },
      { type: 'free', xp: 25, minutes: 5, title: 'Tab: Ode to Joy', text: 'Play this melody on the thin e and B strings:\ne|--0--0--1--3--3--1--0--|\nB|-----------------------|\ne|--0--0--1--3--3--1--0--0--|\nSlow. Melody playing trains your ear like nothing else.' },
    ]},
  { day: 21, phase: 3, title: 'Week 3 Review', minutes: 18,
    goal: 'Consolidate: songs, speed, and the week 3 quiz.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'changes', pair: ['G','Cadd9'], target: 20, xp: 20, title: 'Speed check: G ↔ Cadd9', text: 'Your anchor pair — go for a record.' },
      { type: 'song', song: 'rising-sun', xp: 30, title: 'Rising Sun, full run', text: 'Full song, steady tempo, no stops. Mistakes are allowed; stopping is not.' },
      { type: 'quiz', quiz: 'week3', xp: 30, title: 'Week 3 quiz', text: 'Technique and reading.' },
    ]},

  { day: 22, phase: 4, title: 'Boss Battle: The F Chord', minutes: 18,
    goal: 'Face the chord that defeats most beginners. You have 21 days of finger strength — you are ready.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'chord', chord: 'F', xp: 40, title: 'THE F CHORD (mini version)', text: 'Index finger flattens across the thin two strings at fret 1. Roll it slightly toward its bony edge. Squeeze from the thumb. If only 4 strings ring today, that is a WIN.' },
      { type: 'changes', pair: ['C','F'], target: 6, xp: 30, title: 'Changes: C ↔ F', text: 'Even 6 changes is heroic on day one of F. This pair pays rent forever.' },
      { type: 'song', song: 'rising-sun', xp: 25, title: 'Rising Sun with real F', text: 'Swap Fmaj7 for mini-F. Hear the difference.' },
    ]},
  { day: 23, phase: 4, title: 'Pub Songs & Speed', minutes: 18,
    goal: 'Fast, fun, and loud — The Wild Rover.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'song', song: 'wildrover', xp: 40, title: 'Song: The Wild Rover', text: 'Old Faithful strum at 90 bpm. And it’s no, nay, never — clap clap clap clap!' },
      { type: 'changes', pair: ['C','F'], target: 10, xp: 25, title: 'F rehab: C ↔ F', text: 'Daily F reps from now on. It gets easier shockingly fast.' },
      { type: 'strum', pattern: 'oldFaithful', bpm: 90, minutes: 3, xp: 20, title: 'Old Faithful at 90', text: 'Full speed. Loose wrist, small motions.' },
    ]},
  { day: 24, phase: 4, title: 'Speed Day', minutes: 15,
    goal: 'Push every chord change to performance tempo.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'changes', pair: ['G','C'], target: 20, xp: 25, title: 'G ↔ C at 20+', text: 'This is “real song tempo”. Get there today or die trying (figuratively).' },
      { type: 'changes', pair: ['Am','D'], target: 20, xp: 25, title: 'Am ↔ D at 20+', text: 'Round two.' },
      { type: 'changes', pair: ['E','A'], target: 20, xp: 25, title: 'E ↔ A at 20+', text: 'Round three. Shake your hand out between rounds.' },
      { type: 'free', xp: 15, minutes: 3, title: 'Cooldown jam', text: 'Play anything you love, slow and pretty.' },
    ]},
  { day: 25, phase: 4, title: 'Melody & Chords Together', minutes: 15,
    goal: 'Combine single notes and chords like a real arrangement.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'free', xp: 25, minutes: 5, title: 'Ode to Joy, polished', text: 'Day 20’s melody, now smooth and in rhythm. From memory if you can.' },
      { type: 'free', xp: 30, minutes: 5, title: 'Chord + melody sandwich', text: 'Strum C once, play a bit of melody, strum G, continue. You are arranging now — this is what solo acoustic players actually do.' },
      { type: 'changes', pair: ['C','F'], target: 12, xp: 20, title: 'Daily F reps', text: 'Keep the boss on the ropes.' },
    ]},
  { day: 26, phase: 4, title: 'Tempo Mastery', minutes: 15,
    goal: 'Own the metronome: same song, three tempos.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'song', song: 'saints', xp: 20, title: 'Saints — slow (60)', text: 'Set a slow, meditative pace. Perfect changes only.' },
      { type: 'song', song: 'saints', xp: 20, title: 'Saints — medium (80)', text: 'Normal tempo, add dynamics.' },
      { type: 'song', song: 'saints', xp: 25, title: 'Saints — fast (100)', text: 'Push it! Sloppy allowed, smiling required.' },
      { type: 'read', xp: 15, title: 'Why this works', text: 'Slow practice builds accuracy, fast practice builds courage, medium is where music lives. Rotate all three forever.' },
    ]},
  { day: 27, phase: 4, title: 'Build Your Setlist', minutes: 18,
    goal: 'Choose and rehearse the 3 songs that are officially YOURS.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: '' },
      { type: 'read', xp: 15, title: 'Pick three', text: 'Choose your 3 favorite songs from the Songs tab. Criteria: you love them, and they show off different skills (a strummer, a waltz, the blues...).' },
      { type: 'free', xp: 30, minutes: 6, title: 'Rehearse songs 1 & 2', text: 'Full run-throughs. No stopping for mistakes — flow through them like a performer.' },
      { type: 'free', xp: 25, minutes: 5, title: 'Rehearse song 3', text: 'Your closer. End it with one big final strum and hold it. Showmanship counts.' },
    ]},
  { day: 28, phase: 4, title: 'Train Your Ear', minutes: 15,
    goal: 'Start hearing what you play — the skill that lasts a lifetime.',
    activities: [
      { type: 'free', xp: 20, minutes: 3, title: 'Tune by ear challenge', text: 'Detune your B string slightly, then tune it back using only your ear against the G string (5th fret of G = open B). Check with the tuner after. Close counts!' },
      { type: 'free', xp: 25, minutes: 4, title: 'Happy or sad?', text: 'In the Chords tab, play E then Em, A then Am, D then Dm with your eyes closed. Hear major = bright, minor = moody. That tiny half-step is the whole emotional engine of music.' },
      { type: 'quiz', quiz: 'ear', xp: 30, title: 'Ear & theory quiz', text: 'Majors, minors, and what makes them tick.' },
      { type: 'changes', pair: ['C','F'], target: 15, xp: 20, title: 'Daily F reps', text: 'Almost there.' },
    ]},
  { day: 29, phase: 4, title: 'Dress Rehearsal', minutes: 20,
    goal: 'Full setlist, start to finish, like it’s the real thing.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: 'Performers always tune first.' },
      { type: 'free', xp: 40, minutes: 12, title: 'THE FULL RUN', text: 'All 3 setlist songs back to back. No stops, no restarts. If you can, hit record on your phone — future you will treasure day-29 footage.' },
      { type: 'free', xp: 20, minutes: 3, title: 'Notes & fixes', text: 'One wobbly spot per song — drill just that spot 5 times slowly.' },
    ]},
  { day: 30, phase: 4, title: 'Graduation Day', minutes: 20,
    goal: 'Perform. Celebrate. Look back at how far you’ve come.',
    activities: [
      { type: 'tune', xp: 10, title: 'Tune up', text: 'One last time as a “beginner”.' },
      { type: 'free', xp: 50, minutes: 12, title: 'THE PERFORMANCE', text: 'Play your setlist for someone — a friend, family on a video call, your cat, or a phone camera. Performing once teaches more than a week of practice.' },
      { type: 'quiz', quiz: 'final', xp: 40, title: 'Final exam', text: 'Everything from 30 days. You will crush it.' },
      { type: 'read', xp: 25, title: 'What now?', text: 'You can play guitar. Casually, truly, actually. Next: keep the streak alive with 15 min/day, learn songs YOU love (search “[song name] easy chords”), conquer the full F barre, and consider learning with others — it doubles the fun. The app’s tools work forever. Go make noise. 🎸' },
    ]},
];

const QUIZZES = {
  week1: { name: 'Week 1 Quiz', questions: [
    { q: 'String names, thickest to thinnest?', a: ['E-A-D-G-B-E','E-B-G-D-A-E','A-E-D-G-B-E','E-G-A-D-B-E'], c: 0 },
    { q: 'Where should you press relative to the fret wire?', a: ['Just behind it','Right on top of it','In the middle of the space','Anywhere works'], c: 0 },
    { q: 'Which practice schedule builds skill fastest?', a: ['15 min daily','2 hours every Sunday','1 hour twice a week','Only when inspired'], c: 0 },
    { q: 'For the D chord you strum...', a: ['Top 4 strings only','All 6 strings','Top 2 strings','Bottom 3 strings'], c: 0 },
    { q: 'The goal of one-minute changes is...', a: ['Max changes even if sloppy','Perfect changes only','Strumming loudly','Memorizing lyrics'], c: 0 },
  ]},
  week2: { name: 'Week 2 Quiz', questions: [
    { q: 'In Old Faithful (D-DU-UDU), on the missed strum your arm should...', a: ['Keep swinging without hitting strings','Freeze','Speed up','Switch direction'], c: 0 },
    { q: 'What makes A7 sound “bluesy” vs A?', a: ['A lifted finger adds a 7th note','It’s played louder','It uses more strings','A capo'], c: 0 },
    { q: 'The G ↔ Cadd9 trick works because...', a: ['Fingers 3 & 4 stay planted','They are the same chord','You mute everything','You skip a beat'], c: 0 },
    { q: '3/4 time means...', a: ['3 beats per bar','3 chords per song','Play 3x faster','Only 3 strings'], c: 0 },
    { q: 'An accent means...', a: ['Strumming one beat slightly harder','Playing with a capo','Changing chords','Strumming up'], c: 0 },
  ]},
  week3: { name: 'Week 3 Quiz', questions: [
    { q: 'In tab, the numbers tell you...', a: ['Which fret to press','Which finger to use','How many strums','The tempo'], c: 0 },
    { q: 'In fingerpicking, the thumb usually plays...', a: ['The 3 thickest strings','The thinnest string','All strings','Nothing'], c: 0 },
    { q: 'A percussive “chuck” is made by...', a: ['Relaxing fret-hand pressure while strumming','Hitting the guitar body','Strumming harder','Skipping a strum'], c: 0 },
    { q: 'On a chord chart, X above a string means...', a: ['Don’t play that string','Extra loud','Use your thumb','Bend the string'], c: 0 },
    { q: 'Dsus4 is D with...', a: ['An added pinky note','A muted string','A different bass note','A capo'], c: 0 },
  ]},
  reading: { name: 'Chart Reading Quiz', questions: [
    { q: 'On a chord chart, O above a string means...', a: ['Play it open','Skip it','Optional','Use thumb'], c: 0 },
    { q: 'In tab, which string is the TOP line?', a: ['Thinnest (high e)','Thickest (low E)','The G string','Depends on the song'], c: 0 },
    { q: 'Tab reads...', a: ['Left to right','Right to left','Bottom to top','Any direction'], c: 0 },
    { q: 'A “0” in tab means...', a: ['Open string','Mute the string','Skip the note','Fret zero doesn’t exist'], c: 0 },
  ]},
  ear: { name: 'Ear & Theory Quiz', questions: [
    { q: 'Major chords generally sound...', a: ['Bright / happy','Dark / sad','Out of tune','Quiet'], c: 0 },
    { q: 'The difference between E and Em is...', a: ['One note, a half step apart','Completely different notes','The rhythm','The volume'], c: 0 },
    { q: '5th fret of the G string should match...', a: ['Open B string','Open high E','Open D','Nothing'], c: 0 },
    { q: 'A “7th” chord (like A7) adds...', a: ['A note that creates tension wanting to resolve','More volume','A muted string','A higher octave'], c: 0 },
  ]},
  final: { name: 'Graduation Exam', questions: [
    { q: 'Fastest way to learn a new chord change?', a: ['One-minute change drills, daily','Reading about it','Playing it once a week','Watching videos only'], c: 0 },
    { q: 'Your arm keeps moving on missed strums because...', a: ['It keeps your rhythm locked','It looks cool','It rests your hand','No reason'], c: 0 },
    { q: 'The 12-bar blues in A uses...', a: ['A7, D7, E7','Am, Dm, Em','A, B, C','Only A7'], c: 0 },
    { q: 'Buzzing strings usually mean...', a: ['Press closer behind the fret, use fingertips','Guitar is broken','Strum softer','Give up'], c: 0 },
    { q: 'What builds skill while you sleep?', a: ['Your brain consolidating the day’s practice','Leaving the guitar under the bed','Loud music','Nothing'], c: 0 },
    { q: 'After 30 days, the key to keeping your skills is...', a: ['Short daily practice on songs you love','Never playing again','Only theory study','Buying more guitars'], c: 0 },
  ]},
};

const PHASES = [
  { n: 1, name: 'Foundations',      days: '1–7',   desc: 'Hold it, tune it, first chords, first song.' },
  { n: 2, name: 'Chord Fluency',    days: '8–14',  desc: 'The strum pattern, 7th chords, smooth changes.' },
  { n: 3, name: 'Real Musicianship',days: '15–21', desc: 'Fingerpicking, embellishments, reading, groove.' },
  { n: 4, name: 'Performance',      days: '22–30', desc: 'The F chord, speed, your setlist, graduation.' },
];
